name: Push image to Docker Hub
description: "Login and push image to docker hub"

inputs:
  username:
    description: "Dockerhub username"
  password:
    description: "Dockerhub password"
runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}