name: Push image to Docker Hub
description: "Login and push image to docker hub"

inputs:
  dockerhub_username:
    description: "Dockerhub username"
  dockerhub_token:
    description: "Dockerhub password"
runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Push image to Docker Hub
      run: docker push ${{env.DOCKER_IMAGE_NAME}}:${{env.TAG}}
      shell: bash