name: Build Docker Image
description: "Build a Docker image and check it was created"

inputs:
  path_dockerfile:
    description: "Path to Dockerfile"
  image_name:
    description: "Image name"
  tag_name:
    description: "Docker Image Tag name"

runs:
  using: composite
  steps:
    - name: Define Tag name
      run: |
        if [ -z "${{inputs.tag_name}}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{inputs.tag_name}}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build docker image
      run: docker build . --file ${{inputs.path_dockerfile}} --tag ${{inputs.image_name}}:${{env.TAG}}
      shell: bash

    - name: Check if image was created
      run: docker images | grep ${{inputs.image_name}}
      shell: bash